version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=movies_db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: myuser
      PMA_PASSWORD: password
  app:
    depends_on:
      - mysql
    container_name: movies-api-container
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9000:9000"
    environment:
      - MOVIES_API_MYSQL_USER=myuser
      - MOVIES_API_MYSQL_PASSWORD=password
      - MOVIES_API_MYSQL_HOST=mysql
      - MOVIES_API_MYSQL_PORT=3306
      - MOVIES_API_MYSQL_DB=movies_db
      - MOVIES_API_SERVER_PORT=9000
      - MOVIES_API_ITEMS_PER_PAGE=8
      - MOVIES_API_JWT_SECRET=j8zNlj2Z9NZLXrIJfWwvjaoVqnJxGZyg1Rc4Wmrk
      - MOVIES_API_TOKEN_EXPIRY=3600
    volumes:
      - .:/go/app
    command: "go run main.go"
